feat:TodoItem초안
mangmuse/react-plus-b03 pull request #4
Opened 2024-07-10 05:33 UTC by show1486

중요 별 버튼이랑 ...버튼을 구현이 잘 안돼서 튜터님한테 수업 끝나고 여쭤볼게요

2024-07-10 09:53 UTC, mangmuse approved these changes

2024-07-10 09:55 UTC, minyoungKuk approved these changes

2024-07-11 09:50 UTC, mangmuse requested changes

2024-07-11 09:50 UTC, mangmuse commented on src/components/Header/Header.tsx
> +const Header = ({ children, title }) => {
Header 컴포넌트 props 타입 정의 부탁드려요!

2024-07-12 06:32 UTC, closed without merging